targets:
  100:
    type: "capsule"
    name: "people mover"
    markers:
      47:
        alignment:
          [ 1.0, 0.0, 0.0, 0.0,
            0.0, 1.0, 0.0, -0.075,
            0.0, 0.0, 1.0, 0.495,
            0.0, 0.0, 0.0, 1.0 ]
        side: "front"

      48:
        alignment:
          [ 0.0, -1.0, 0.0, -1.42,
            1.0, 0.0, 0.0, 0.67,
            0.0, 0.0, 1.0, 0.604,
            0.0, 0.0, 0.0, 1.0 ]
        side: "left"

      49:
        alignment:
          [ 0.0, 1.0, 0.0, -1.42,
            -1.0, 0.0, 0.0, -0.67,
            0.0, 0.0, 1.0, 0.604,
            0.0, 0.0, 0.0, 1.0 ]
        side: "right"

  101:
    type: "capsule"
    name: "cargo mover"
    markers:
      44:
        alignment:
          [ 1.0, 0.0, 0.0, 0.0,
            0.0, 1.0, 0.0, -0.075,
            0.0, 0.0, 1.0, 0.51,
            0.0, 0.0, 0.0, 1.0 ]
        side: "front"

      45:
        alignment:
          [ 0.0, -1.0, 0.0, -1.32,
            1.0, 0.0, 0.0, 0.665,
            0.0, 0.0, 1.0, 0.43,
            0.0, 0.0, 0.0, 1.0 ]
        side: "left"

      46:
        alignment:
          [ 0.0, 1.0, 0.0, -1.29,
            -1.0, 0.0, 0.0, -0.665,
            0.0, 0.0, 1.0, 0.43,
            0.0, 0.0, 0.0, 1.0 ]
        side: "right"
